# Set Up the CI Pipeline
# + Trigger: The workflow should run on pull requests to the `main` branch.
# + Job Name: `test`
# + Actions:
#   - Run `pytest` to execute the existing tests.
#   - Fail if there are issues in the application.
#   - Succeed if the application passes all tests.
#

name: CI Pipeline

on:
  pull_request:
    branches:
      - main 
     # Trigger on pull request to `main`

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
